version: "3.4"
services:
  pub-anycast:
    container_name: pub-anycast
    build: .
    restart: unless-stopped
    tty: true
    networks:
      host_bridge:
        ipv4_address: 10.253.169.2
        ipv6_address: fd5f:4366:7556:ac7b:eafe:f52a:ac7b:2
    volumes:
      - ./run/bird:/run/bird
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    privileged: true
    dns:
      - ::1
      - 127.0.0.1
    cap_add: # 并没有程序托管，默认的cli容器，做管理的时候会造成点麻烦
      - NET_ADMIN
  pub-anycast-update: # 独立开来为了更新容器的时候不影响其他容器
    container_name: pub-anycast-update
    build: .
    restart: unless-stopped
    command: /usr/local/bin/update.sh
    network_mode: service:pub-anycast
    privileged: true
    depends_on:
      - pub-anycast
    volumes:
      - ./run/bird:/run/bird
    cap_add:
      - NET_ADMIN
  pub-anycast-bird:
    container_name: pub-anycast-bird
    build: .
    command: /sbin/bird -d
    restart: unless-stopped
    network_mode: service:pub-anycast
    privileged: true
    volumes:
      - ./run/bird:/run/bird
    depends_on:
      - pub-anycast
      - pub-anycast-update
    cap_add:
      - NET_ADMIN
  pub-anycast-dnsmasq:
    container_name: pub-anycast-dnsmasq
    build: .
    command: /usr/sbin/dnsmasq -d
    restart: unless-stopped
    network_mode: service:pub-anycast
    depends_on:
      - pub-anycast
      - pub-anycast-update
      - pub-anycast-bird
    volumes:
      - /root/auto_boot/pubic_dn42_network/config/anycast/dnsmasq.d:/etc/dnsmasq.d
  pub-anycast-caddy:
    container_name: pub-anycast-caddy
    image: docker.io/library/caddy
    network_mode: service:pub-anycast
    depends_on:
      - pub-anycast
    volumes:
      - /root/auto_boot/pubic_dn42_network/config/anycast/caddy/:/etc/caddy/
  pub-anycast-bird-lg:
    image: docker.io/xddxdd/bird-lg-go:latest
    container_name: bird-lg
    restart: always
    environment:
      - BIRDLG_SERVERS=ams1,fsn1,sjc1,sjc2,dfw1,mci1,ewr1,sin1,hkg1,hkg2,hkg3,tpe1,can1
      - BIRDLG_DOMAIN=pub.23751.net # 节点 endpiont 后缀
      - BIRDLG_TITLE_BRAND=23751NET Looking Glass # 标签栏上显示的名称
      - BIRDLG_NAVBAR_BRAND=23751NET Looking Glass # 页面上显示的名称
      - BIRDLG_WHOIS=whois.lantian.dn42 # Whois 服务器地址
      - BIRDLG_DNS_INTERFACE=asn.dn42
    network_mode: service:pub-anycast

networks:
  host_bridge:
    driver: bridge
    enable_ipv6: true
    internal: false # 不可以设置为true，桥接网卡的fe80都不通了
    driver_opts:
      com.docker.network.bridge.name: "br-bgp"
    ipam:
      driver: default
      config:
        - subnet: 10.253.169.1/30
        - subnet: fd5f:4366:7556:ac7b:eafe:f52a:ac7b::/126